Added logic to remove decayed host resources
wasmCloud/lattice-observer pull request #22
Opened 2022-09-14 23:44 UTC by brooksmtownsend

Should be merged after #21 so the test suite runs

This PR adds a bit of logic to fully purge host resources from the lattice when a host decays through all decay states. Any host that re-joins the lattice will emit a heartbeat to restore these resources, but if it fades out of existence those actors and providers should be considered null and void

2022-09-15 16:36 UTC, connorsmith256 requested changes

2022-09-15 16:36 UTC, connorsmith256 commented on lib/lattice_observer/observed/decay.ex
> +      List.foldl(fully_decayed, l, fn {hk, _host}, lattice ->
Suggestion: I have a hard time following single-character variable names, and not being very familiar with Elixir's fold syntax, got especially got confused by `l` vs `lattice`

```suggestion
      List.foldl(fully_decayed, lattice, fn {host_key, _host}, acc ->
```

2022-09-15 16:36 UTC, connorsmith256 commented on lib/lattice_observer/observed/decay.ex
> +  defp age_hosts(hosts, event_time, decay_rate) do
This reads as imperative, but it's functional (as all things should be 😉). How about renaming this to something like `partition_decayed_hosts`?

2022-09-15 19:45 UTC, connorsmith256 approved these changes

2022-09-16 13:19 UTC, autodidaddict approved these changes

2022-09-16 13:45 UTC, merged